Repository impierce/did-manager, pull requests merged in 2024-05, with the labels that each got.

#13 feat: remove dependency on `oid4vc-core`
  Cargo.lock
  producer/Cargo.toml
  producer/src/lib.rs
  producer/src/oid4vc_core.rs
  producer/src/secret_manager.rs
  shared/src/test_utils.rs
Labels: Dependencies, Removed

#15 chore(did_web): use `spruceid/ssi` fork (excluded `openssl`)
  Cargo.lock
  did_web/Cargo.toml
Labels: Dependencies

#18 feat: add `stronghold_ext_storage` for `Es256` support
  .gitignore
  Cargo.lock
  Cargo.toml
  did_iota/Cargo.toml
  did_iota/src/producer/produce.rs
  did_jwk/Cargo.toml
  did_jwk/src/consumer.rs
  did_jwk/src/producer.rs
  did_key/Cargo.toml
  did_key/src/consumer.rs
  did_key/src/producer.rs
  did_web/Cargo.toml
  did_web/src/producer.rs
  identity_stronghold_ext/Cargo.toml
  identity_stronghold_ext/README.md
  identity_stronghold_ext/src/lib.rs
  identity_stronghold_ext/src/stronghold_jwk_storage.rs
  producer/Cargo.toml
  producer/src/did_document.rs
  producer/src/secret_manager.rs
  producer/src/signature.rs
  producer/tests/res/multi.stronghold
  shared/Cargo.toml
  shared/src/error.rs
  shared/src/lib.rs
  shared/src/test_utils.rs
  shared/tests/res/multi.stronghold
Labels: Addition
